# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Marco Welter <mawe@tamaly.de>

name="bcraft"
version="0.6.0"
release="1"

arch="any"
base="any"

description="Basecraft build and package management tool"
license="GPL-3.0-or-later"
maintainer="Marco Welter <mawe@tamaly.de>"

source_mode="recipe"
